version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: express-ts:test
    ports:
      - 3002:3002
    depends_on:
      - mysql
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=test
      - DB_SYNC=true

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - pg_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  webnet:

volumes:
  pg_data:
    driver: local
